baseURL = "https://asakomikami.com"
languageCode = "en-us"
title = "Asako Mikami"
relativeURLs = true
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
disqusShortname = "amikami102"

[params]
  subtitle = "Mastered out of a PhD program in political science, now applying for data scientist/analyst position."

[[params.topmenu]]
  name = "About"
  url = "/about/"

[[params.topmenu]]
  name = "Recent posts"
  url = "/post/"
  
[[params.topmenu]]
  name = "Categories"
  url = "/categories/"
  

[permalinks]
    post = "/:year/:month/:day/:slug/"

