baseURL = "https://asakomikami.com"
languageCode = "en-us"
title = "Asako Mikami"
relativeURLs = true
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
disqusShortname = "amikami102"

[taxonomies]
  series = "series"
  tag = "tags"

[[params.topmenu]]
  name = "About"
  url = "/about/"

[[params.topmenu]]
  name = "All posts"
  url = "/posts/"
  
[[params.topmenu]]
  name = "Series"
  url = "/series/"

  

[permalinks]
    post = "/:year/:month/:day/:slug/"

