---
title: "About"
comment: false
---



My name is Asako. I recently mastered out of a PhD program in political science. I received my BA from Smith College where I majored in Government and minored in Mathematics. 

I have been studying political science for almost 9 years, specializing in research methodology and principles of reproducible research for the last 5 years. I want to help others with the knowledge and skills I cultivated from my methodology studies. 

You can reach me via
[Twitter](https://twitter.com/asak0mikami) or [email](mailto:asakomikami@gmail.com).


This website is my little corner on the Internet where I publish my tutorials and pieces of writing. As of `r format(Sys.time(), '%B %d, %Y')`, the topics are limited to Python/R tutorials and reviews of academic research papers, but I plan to expand my content range over the next few months.

# Acknowledgements

This website was built using the `blogdown` package in R and Hugo with [paperesque](https://themes.gohugo.io/paperesque/) theme by Fabian Tamp. Here are some awesome resources that helped me get this website up and running. 

- Dave Robinson's blogpost, ["Advice to aspiring data scientists: start a blog"](http://varianceexplained.org/r/start-blog/) for the inspiration to start this blog
- Alison Presmane Hill's blogpost, ["Up and running with blogdown"](https://alison.rbind.io/post/up-and-running-with-blogdown/) on how to get quickly started with `blogdown` in R Studio
- Brooke Watson's blogost, ["Custom domain hosting with GitHub and Namecheap"](https://blog.brooke.science/posts/custom-domain-hosting-with-github-and-namecheap/) on how to deploy your website with a custom domain 
- Amber Thomas's blogpost, ["Adding Syntax Highlighting to Blogdown Posts"](https://amber.rbind.io/2017/11/15/syntaxhighlighting/) on how to enable syntax highlighting


