---
title: 'Caroline Fry, "Building Bridges: The impact of return migration by African scientists"'
date: '2020-04-18'
slug: jmp-review-caroline-fry
series: 
        - JMP by women in economics
meta: TRUE
math: TRUE
draft: TRUE
---

*This blog post is part of my "JMP by Women in Econ" series where I summarize and review some of the job market papers written by women PhD candidates in Economics. The papers are selected from Jennifer Doleac's [Twitter thread](https://twitter.com/jenniferdoleac/status/1187863251947806720). DISCLAIMER: I am not reading this from the perspective of an economist, let alone of a job committee member. I just like reading cool articles that use observational data to tackle challenging research problems.* :bowtie:

The third installment in this series is Caroline Fry's paper, ["Building Bridges: The impact of migration by African scientists."](http://carolinefry.mit.edu/research-0) I chose this paper to add to my personal collection of "Clever Research Designs on Network Effects," which so far includes Azoulay, Zivin, and Wang (2010) "Superstar Extinction" and Jaffe et al. (2019) "Geographic Localization of Knowledge Spillovers as Evidenced by Patent Citations." Just as Carters paper [in the previous installment of the series]({{< ref "/post/2020-04-18-carter" >}}) was an instructive example for testing path dependence hypothesis, Fry's paper

Here's an excerpt from the abstract: 

> Despite significant interest in the potential for 'returnee' scientists moving back to developing countries to connect developed and developing countries, prior work has found limited evidence of success. I shift the focus to the broader network of the returnee, and study the extent to which the return home of American-trained HIV researchers to African institutions impacts publication outcomes of non-migrant scientists in Africa. 

Research questions on the effects of networks are hard to translate to a causal inference question because we select ourselves and are selected into networks. There is a 




