---
title: "JMP by Women in Economics"
math: true
---

This is a series of blog posts where I review job market papers written by women graduating from Economics PhD programs in 2020. The papers are selected from Jennifer Doleac's [Twitter thread](https://twitter.com/jenniferdoleac/status/1187863251947806720). 

There are both theoretical and empirical papers, but since economics is not my field of expertise, I will almost always be reviewing an empirical paper where my knowledge of statistics and causal inference can help me comprehend the research design and interpret the results. The target audience would be a graduate student, or even an undergraduate, who is familiar with the principles of causal inferences and the challenges of identifying causal effect with observational data.  

When I review these papers, I will state the research question in the form of "What is the effect of manipulating $T$ on $Y$?" The formula is inspired by David Holland's famous declaration, "[No causation without manipulation](www.jstor.org/stable/2289064)." Most research questions are not worded awkwardly like this, but I think putting the research question in manipulationist framework is an important exercise when writing and reading social science papers. First, it forces me to think carefully about what are the treatment ($T$) and outcome ($Y$) variables in the study and how they are measured. Second, it makes me think explicitly about what features of the treatment variable is being manipulated---if it can be manipulated. 


Next, I explain what some of the challenges are to identifying the causal effect with observational data, namely a selection bias, omitted variable bias, or simultaneity. Then, I describe the author's research design by stating what the treated and control groups are and writing out the regression equation. Since there's a lot to unpack in each paper, I pick and share only the parts of the results section that I find interesting or surprising with screenshots of the relevant figures and tables. All of the images of tables and figures come from the most recent versions of the papers as of each blog post's publication date. 

I try to end the blog post with my own comments about each paper such as its clarity in writing, the novelty of the data or the way the data is used, and other things I thought were very cool. 
